In [1]:
import pandas as pd
import numpy as np
from numpy.random import choice
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
data = pd.read_excel("Data.xlsx")

In [3]:
data.head()

,Unnamed: 0,Doc. Date,Material,Order qty,Ship-to nu,PCS delivered,HL delivered,delivery_days,delivery_flag,lead_time_creation_vs_rdd_flag,...,Container Size,Variétés,Segment LE,Latitude,Longitude,Degre Alc,TTC,Brut + TE,Net + TE - Hors majoration de rompu de palette,DA
0,0,2021-01-11,10946,5.0,29606863,350.0,21.0,7,1,1,...,"6,000 L",Blonde,PREMIUM,50.6455,2.9619,6.6,18.137448,15.582,15.114540,0.0
1,1,2021-01-11,19898,2.0,29606863,140.0,8.4,7,1,1,...,NaN,NaN,NaN,50.6455,2.9619,5.0,17.396467,14.688,14.497056,0.0
2,2,2021-01-11,80176,4.0,29606863,280.0,16.8,7,1,1,...,NaN,NaN,NaN,50.6455,2.9619,0.0,12.279859,10.368,10.233216,0.0
3,3,2021-01-11,66989,1.0,29606863,70.0,4.2,7,1,1,...,"6,000 L",-,SUPER PREMIUM,50.6455,2.9619,8.0,21.996000,18.330,18.330000,0.0
4,4,2021-01-08,11766,70.0,29378784,70.0,4.2,6,1,1,...,NaN,NaN,NaN,50.6978,2.2423,5.2,17.359200,14.466,14.466000,0.0

In [4]:
cols = list(data.columns)
pd.Series(cols)

0                                            Unnamed: 0
1                                             Doc. Date
2                                              Material
3                                             Order qty
4                                            Ship-to nu
5                                         PCS delivered
6                                          HL delivered
7                                         delivery_days
8                                         delivery_flag
9                        lead_time_creation_vs_rdd_flag
10                                             MACO/HL
11                                           Groupement
12                                          Postal Code
13                                               Street
14                                      Sous groupement
15                                      M2_Territory_ID
16                                      M1_Territory_ID
17                                                 Dépt
18                                                Brand
19                                              Subrand
20    SEGMENTS : Pils / Spécialités / Superspécialit...
21                                       Container Type
22                                       Container Size
23                                             Variétés
24                                           Segment LE
25                                             Latitude
26                                            Longitude
27                                            Degre Alc
28                                                  TTC
29                                            Brut + TE
30       Net + TE - Hors majoration de rompu de palette
31                                                   DA
dtype: object

In [5]:
similar_features_index = [18, 19, 20, 23, 24, 27]
similar_features = [cols[simindex] for simindex in similar_features_index ]
similar_features

['Brand',
 'Subrand',
 'SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult',
 'Variétés',
 'Segment LE',
 'Degre Alc']

In [6]:
len(data.Material.unique())

179

In [7]:
material_10 = choice(np.array(data.Material.unique()))

In [8]:
material_10

74529

In [9]:
mat_data = data[data['Material'] == material_10]

In [10]:
mat_data.head(10)

,Unnamed: 0,Doc. Date,Material,Order qty,Ship-to nu,PCS delivered,HL delivered,delivery_days,delivery_flag,lead_time_creation_vs_rdd_flag,...,Container Size,Variétés,Segment LE,Latitude,Longitude,Degre Alc,TTC,Brut + TE,Net + TE - Hors majoration de rompu de palette,DA
4778,4778,2020-07-15,74529,12.0,29379853,12.0,0.9504,6,1,1,...,"0,330 L",Triple,PREMIUM LAGER,47.5382,6.4026,4.5,25.084800,20.784,20.784000,0.12
6097,6097,2020-07-16,74529,36.0,29563817,36.0,2.8512,4,1,0,...,"0,330 L",Triple,PREMIUM LAGER,44.7544,-0.5313,4.5,25.084800,20.784,20.784000,0.12
6135,6135,2020-07-16,74529,12.0,29379283,12.0,0.9504,6,1,1,...,"0,330 L",Triple,PREMIUM LAGER,45.0717,5.6425,4.5,25.084800,20.784,20.784000,0.12
7398,7398,2020-07-21,74529,1.0,29379834,1.0,0.0792,7,1,1,...,"0,330 L",Triple,PREMIUM LAGER,45.6221,6.7996,4.5,25.041485,20.784,20.747904,0.12
7535,7535,2020-07-21,74529,12.0,29379625,12.0,0.9504,6,1,1,...,"0,330 L",Triple,PREMIUM LAGER,47.6089,2.1729,4.5,25.084800,20.784,20.784000,0.12
7660,7660,2020-07-22,74529,12.0,29379625,12.0,0.9504,7,1,1,...,"0,330 L",Triple,PREMIUM LAGER,47.6089,2.1729,4.5,25.084800,20.784,20.784000,0.12
8580,8580,2020-07-24,74529,12.0,29379625,12.0,0.9504,5,1,0,...,"0,330 L",Triple,PREMIUM LAGER,47.6089,2.1729,4.5,25.084800,20.784,20.784000,0.12
12636,12636,2020-08-06,74529,10.0,29379819,10.0,0.7920,6,1,1,...,"0,330 L",Triple,PREMIUM LAGER,49.0435,2.1213,4.5,25.084800,20.784,20.784000,0.12
16631,16631,2020-08-25,74529,24.0,29379862,24.0,1.9008,6,1,1,...,"0,330 L",Triple,PREMIUM LAGER,46.4627,0.2287,4.5,25.084800,20.784,20.784000,0.12
20032,20032,2020-09-16,74529,12.0,29379841,12.0,0.9504,8,0,1,...,"0,330 L",Triple,PREMIUM LAGER,NaN,NaN,4.5,25.084800,20.784,20.784000,0.12

In [11]:
mat_data = mat_data[similar_features]
mat_data

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
4778,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
6097,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
6135,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
7398,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
7535,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
7660,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
8580,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
12636,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
16631,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
20032,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
20675,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
24084,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
24345,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
26105,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
26106,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
28214,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
28258,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
28259,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
32092,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
32093,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
32859,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
34163,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
35165,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
40976,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
42074,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
46678,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
47130,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
48655,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
52182,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
52843,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
52855,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
52938,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
55848,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
56743,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
57757,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
58251,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
61400,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
61939,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
62905,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
65829,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
69175,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
72316,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5
73199,GINETTE,GINETTE LAGER,Craft,Triple,PREMIUM LAGER,4.5

In [12]:
material_example = data.Material.unique()[0]
data[data['Material']==material_example][similar_features]

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
8,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
17,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
41,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
53,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
...,...,...,...,...,...,...
73625,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73637,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73643,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,NaN
73651,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73654,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6

In [13]:
# data[data['Material']==material_example].loc[:,similar_features]

In [14]:
# data[data['Material']==material_example][similar_features].fillna(method = 'ffill')

In [15]:
# df_temp = data[data['Material']==material_example][similar_features].fillna(method = 'ffill')
# data.loc[df_temp.index,similar_features] = df_temp
# data.loc[df_temp.index,similar_features]

In [16]:
# data[data['Material']==material_example].loc[:,similar_features]

In [17]:
# data[data['Material']==material_example][similar_features]

In [18]:
for material in list(data.Material.unique()):
    df_temp = data[data['Material']==material][similar_features].fillna(method = 'ffill')
    data.loc[df_temp.index,similar_features] = df_temp

In [19]:
material_example = data.Material.unique()[0]
data[data['Material']==material_example][similar_features]

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
8,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
17,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
41,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
53,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
...,...,...,...,...,...,...
73625,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73637,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73643,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73651,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73654,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6

In [20]:
material_example = data.Material.unique()[0]
data[data['Material']==material_example][similar_features]

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
8,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
17,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
41,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
53,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
...,...,...,...,...,...,...
73625,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73637,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73643,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73651,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73654,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6

In [21]:
# data.Material.unique()

In [22]:
material_10 = 10946

In [23]:
mat_data = data[data['Material'] == material_10]
mat_data = mat_data[similar_features]
mat_data

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
8,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
17,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
41,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
53,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
...,...,...,...,...,...,...
73625,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73637,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73643,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73651,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6
73654,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6

In [24]:
len(data.Material.unique())

179

In [25]:
cols_to_keep = similar_features + ['Material']
cols_to_keep

['Brand',
 'Subrand',
 'SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult',
 'Variétés',
 'Segment LE',
 'Degre Alc',
 'Material']

In [26]:
similarities_df = data[cols_to_keep]
display(len(similarities_df.Material.unique()))
similarities_df.drop_duplicates(inplace = True)
similarities_df[similarities_df.duplicated('Material')].Material.unique()

179

<ipython-input-26-3f70cd0338ea>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  similarities_df.drop_duplicates(inplace = True)

array([], dtype=int64)

In [27]:
similarities_df

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc,Material
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6,10946
1,NaN,NaN,NaN,NaN,NaN,5.0,19898
2,NaN,NaN,NaN,NaN,NaN,0.0,80176
3,TRIPLE KARMELIET,TRIPLE KARMELIET,Craft,-,SUPER PREMIUM,8.0,66989
4,NaN,NaN,NaN,NaN,NaN,5.2,11766
...,...,...,...,...,...,...,...
68396,NaN,NaN,NaN,NaN,NaN,NaN,3643
68397,NaN,NaN,NaN,NaN,NaN,NaN,15757
68542,NaN,NaN,NaN,NaN,NaN,0.0,77393
71226,NaN,NaN,NaN,NaN,NaN,NaN,65643
71470,NaN,NaN,NaN,NaN,NaN,NaN,72326

In [28]:
features = similar_features
df = similarities_df
features

['Brand',
 'Subrand',
 'SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult',
 'Variétés',
 'Segment LE',
 'Degre Alc']

In [29]:
def combine_features(row):
    cf =  row['Brand']+" "+row['Subrand'] + " "+row['SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult']+" "+row['Variétés'] + " " + row['Segment LE']
    return cf

In [30]:
for feature in features:
    df[feature] = df[feature].fillna('')
df["combined_features"] = df.apply(combine_features,axis=1)

<ipython-input-30-9c34e7555a69>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[feature] = df[feature].fillna('')
<ipython-input-30-9c34e7555a69>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["combined_features"] = df.apply(combine_features,axis=1)

In [31]:
df

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc,Material,combined_features
0,LEFFE,LEFFE BLONDE,Spécialités,Blonde,PREMIUM,6.6,10946,LEFFE LEFFE BLONDE Spécialités Blonde PREMIUM
1,,,,,,5,19898,
2,,,,,,0,80176,
3,TRIPLE KARMELIET,TRIPLE KARMELIET,Craft,-,SUPER PREMIUM,8,66989,TRIPLE KARMELIET TRIPLE KARMELIET Craft - SUPE...
4,,,,,,5.2,11766,
...,...,...,...,...,...,...,...,...
68396,,,,,,,3643,
68397,,,,,,,15757,
68542,,,,,,0,77393,
71226,,,,,,,65643,
71470,,,,,,,72326,

In [32]:
cv = CountVectorizer() 
count_matrix = cv.fit_transform(df["combined_features"])

In [33]:
count_matrix

<179x48 sparse matrix of type '<class 'numpy.int64'>'
	with 381 stored elements in Compressed Sparse Row format>

In [ ]:
cosine_sim = cosine_similarity(count_matrix)

In [ ]:
def find_title_from_index(index):
    return df[df.index == index]["Material"].values[0]
def find_index_from_title(Material):
    return df[df.Material == Material]["index"].values[0]

In [ ]:
material = 45918
material_index = find_index_from_title(material)