In [39]:
import pandas as pd
import numpy as np
from numpy.random import choice

In [2]:
data = pd.read_excel("Data.xlsx")

In [12]:
data.head()

,Unnamed: 0,Doc. Date,Material,Order qty,Ship-to nu,PCS delivered,HL delivered,delivery_days,delivery_flag,lead_time_creation_vs_rdd_flag,...,Container Size,Variétés,Segment LE,Latitude,Longitude,Degre Alc,TTC,Brut + TE,Net + TE - Hors majoration de rompu de palette,DA
0,0,2021-01-11,10946,5.0,29606863,350.0,21.0,7,1,1,...,"6,000 L",Blonde,PREMIUM,50.6455,2.9619,6.6,18.137448,15.582,15.114540,0.0
1,1,2021-01-11,19898,2.0,29606863,140.0,8.4,7,1,1,...,NaN,NaN,NaN,50.6455,2.9619,5.0,17.396467,14.688,14.497056,0.0
2,2,2021-01-11,80176,4.0,29606863,280.0,16.8,7,1,1,...,NaN,NaN,NaN,50.6455,2.9619,0.0,12.279859,10.368,10.233216,0.0
3,3,2021-01-11,66989,1.0,29606863,70.0,4.2,7,1,1,...,"6,000 L",-,SUPER PREMIUM,50.6455,2.9619,8.0,21.996000,18.330,18.330000,0.0
4,4,2021-01-08,11766,70.0,29378784,70.0,4.2,6,1,1,...,NaN,NaN,NaN,50.6978,2.2423,5.2,17.359200,14.466,14.466000,0.0

In [19]:
cols = list(data.columns)
pd.Series(cols)

0                                            Unnamed: 0
1                                             Doc. Date
2                                              Material
3                                             Order qty
4                                            Ship-to nu
5                                         PCS delivered
6                                          HL delivered
7                                         delivery_days
8                                         delivery_flag
9                        lead_time_creation_vs_rdd_flag
10                                             MACO/HL
11                                           Groupement
12                                          Postal Code
13                                               Street
14                                      Sous groupement
15                                      M2_Territory_ID
16                                      M1_Territory_ID
17                                                 Dépt
18                                                Brand
19                                              Subrand
20    SEGMENTS : Pils / Spécialités / Superspécialit...
21                                       Container Type
22                                       Container Size
23                                             Variétés
24                                           Segment LE
25                                             Latitude
26                                            Longitude
27                                            Degre Alc
28                                                  TTC
29                                            Brut + TE
30       Net + TE - Hors majoration de rompu de palette
31                                                   DA
dtype: object

In [28]:
similar_features_index = [18, 19, 20, 23, 24, 27]
similar_features = [cols[simindex] for simindex in similar_features_index ]
similar_features

['Brand',
 'Subrand',
 'SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult',
 'Variétés',
 'Segment LE',
 'Degre Alc']

In [44]:
material_10 = choice(np.array(data.Material.unique()))

In [50]:
material_10

78356

In [45]:
mat_data = data[data['Material'] == material_10]

In [46]:
mat_data.head(10)

,Unnamed: 0,Doc. Date,Material,Order qty,Ship-to nu,PCS delivered,HL delivered,delivery_days,delivery_flag,lead_time_creation_vs_rdd_flag,...,Container Size,Variétés,Segment LE,Latitude,Longitude,Degre Alc,TTC,Brut + TE,Net + TE - Hors majoration de rompu de palette,DA
245,245,2021-01-19,78356,70.0,29379853,70.0,4.2,9,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,47.5382,6.4026,5.0,16.246267,14.472,13.538556,0.0
377,377,2021-01-26,78356,70.0,29379283,70.0,4.2,6,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,45.0717,5.6425,5.0,16.246267,14.472,13.538556,0.0
472,472,2021-01-28,78356,10.0,29379820,10.0,0.6,6,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,46.6000,-0.5582,5.0,16.246267,14.472,13.538556,0.0
492,492,2021-01-28,78356,20.0,29379646,20.0,1.2,6,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,50.6760,2.8451,5.0,16.246267,14.472,13.538556,0.0
628,628,2021-02-03,78356,140.0,40016990,140.0,8.4,7,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,49.7394,2.2184,5.0,17.366400,14.472,14.472000,0.0
647,647,2021-02-03,78356,10.0,29379695,10.0,0.6,5,1,0,...,"6,000 L",La Légère,PREMIUM LAGER,46.6501,5.4404,5.0,16.246267,14.472,13.538556,0.0
718,718,2021-02-08,78356,10.0,29378785,10.0,0.6,4,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,50.6177,2.3964,5.0,16.246267,14.472,13.538556,0.0
721,721,2021-02-08,78356,40.0,29379820,40.0,2.4,7,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,46.6000,-0.5582,5.0,16.246267,14.472,13.538556,0.0
925,925,2021-02-16,78356,70.0,29379067,70.0,4.2,7,1,1,...,"6,000 L",La Légère,PREMIUM LAGER,48.0280,7.5004,5.0,16.246267,14.472,13.538556,0.0
1000,1000,2021-02-18,78356,30.0,29379646,30.0,1.8,7,0,1,...,"6,000 L",La Légère,PREMIUM LAGER,50.6760,2.8451,5.0,16.246267,14.472,13.538556,0.0

In [47]:
mat_data = mat_data[similar_features]
mat_data

,Brand,Subrand,SEGMENTS : Pils / Spécialités / Superspécialités/Bouteille Young adult,Variétés,Segment LE,Degre Alc
245,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
377,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
472,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
492,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
628,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
...,...,...,...,...,...,...
70743,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,NaN
70744,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,NaN
71566,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
72008,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0
72045,LEFFE,LEFFE LA LEGERE,Spécialités,La Légère,PREMIUM LAGER,5.0

In [53]:
mat_data['Degre Alc'].fillna(method= 'backfill',inplace = True)

In [54]:
mat_data['Degre Alc'].isna()

245      False
377      False
472      False
492      False
628      False
         ...
70743    False
70744    False
71566    False
72008    False
72045    False
Name: Degre Alc, Length: 202, dtype: bool

In [49]:
similarities_df = data[similar_features]
similaritoes_df